### PR TITLE
Implement default constructor for arrays

### PR DESCRIPTION
**Pull request by voidseg**
I'd like to use an array of multiple movingAvg objects for multiple analog inputs. So I've added a default constructor and movingAvg::begin(int interval) which can be used for initializing the objects in the ::setup() function.

### CODE REVIEW

**Comment by JChristensen** [comment]
I only see this as necessary if the requirement is to have an array of movingAvg objects, that don't all have the same interval. Is that the case?

**Comment by voidseg** [comment]
In my case all objects should have the same interval. I just spent some time figuring out, which syntax can be used to initialize all objects at once. Apparently this compiles in my Arduino IDE but doesn't seem to be valid C++ (haven't checkt it on a board yet):

movingAvg avg[COUNT](INTERVAL);

Besides I think, the default constructor approach with the parametrized begin() function does fit better in the Arduino world and should be more convenient to most users. 

With the reset() call you are absolutely right. I totally missed that. Do you prefer the initializer list or the reset() call? I will fix that.

**Comment by JChristensen** [comment]
Why do you say that's not valid C++?
I did check that syntax and it seems to work, e.g.:
```c++
#include <movingAvg.h>      // https://github.com/JChristensen/movingAvg

movingAvg myAvgs[6](10);    // six moving averages with interval 10

void printAverages()
{
    for (int i=0; i<6; i++)
    {
        Serial.print("avg");
        Serial.print(i);
        Serial.print("=");
        Serial.println(myAvgs[i].getAvg());
    }
}

void setup()
{
    Serial.begin(115200);
    for (int i=0; i<6; i++) myAvgs[i].begin();
    myAvgs[0].reading(10);
    myAvgs[1].reading(20);
    printAverages();
    myAvgs[0].reading(20);
    myAvgs[1].reading(40);
    printAverages();
}

void loop()
{
}
```

**Comment by voidseg** [comment]
Yes it seems to work on Arduino, but I tried to get the following example working with GCC. It only compiles with -fpermissive which still produces a warning. That's why I think, this is not standard C++ but some compiler specific option.

```
#include <iostream>
#include <string>

class Clazz {
public:
    Clazz() {
        std::cout << "default ctor" << std::endl;
    }
    Clazz(int i) {
        std::cout << "special ctor i=" << i << std::endl;
    }
};

int main() {
        Clazz o1;
        Clazz o2(2);
        Clazz o3 = { };
        Clazz o4 = { 4 };

        Clazz a1[1];
        Clazz a2[2](5); // only compiles with -fpermissive
        Clazz a3[3] = { 6, 7, 8 };

        return 0;
}
```

**Comment by JChristensen** [comment]
According to Stroustrup (3rd edition, section 10.4.7), "Except by using an initializer list, there is no way to specify explicit arguments for a constructor in an array declaration."
So the proper syntax would be similar to
```c++
Clazz a3[3] = { 6, 7, 8 };
```
In your case, you want every member of the array to have the same interval, so
```c++
 movingAvg myAvgs[4] = {10, 10, 10, 10};    // four objects, each with interval 10
```
The Arduino IDE uses the -w flag to suppress warnings so that's why the warning doesn't show there (even though I have Compiler Warnings set to All in the Preferences, so I'm not sure I understand that.)

The thing I didn't like about the PR was that the initialization for single objects was different from that for arrays, with the interval being passed as a constructor parameter in one case and with begin() in the other. That provided backwards compatibility but I might prefer to break backwards compatibility for the sake of consistency.

Personally I slightly prefer passing the interval to the constructor as opposed to begin; it just feels more natural to me.

Now that we've identified the proper syntax, I don't think any change is needed. Agree?

**Comment by voidseg** [comment]
I totally agree with you, that the initialization of movingAvg should be consistent from a clean code perspective. I also think, that C++ should have a convenient way of initializing arrays with constructor arguments. It's a shame, that this syntax is not standardized.

However I think I leave my solution for the moment as is, because with the initializer list syntax it is very easy to mess up the number of objects. Since there is no bounds check and we run on bare hardware, I feel much more comfortable using a for loop and begin().

What do you think. Should we keep this PR thread for other people also dealing with this issue or just delete this PR?

**Comment by JChristensen** [comment]
As for standardized syntax, C++ does sometimes also seem to me that it's all over the place ;-) but I think that the proper approach is
```c++
movingAvg singleAvg(6);                 // a single movingAvg object
movingAvg myAvgs[4] = {6, 6, 6, 6};     // an array of movingAvg objects
```
Whether that seems consistent or not I guess is a personal perception thing.

Bounds checking should not be an issue. Using `sizeof()` is a canonical way of iterating over an array, for example:
```c++
#include <movingAvg.h>      // https://github.com/JChristensen/movingAvg
#include <Streaming.h>      // http://arduiniana.org/libraries/streaming/

// any number other than [4] will cause a compile error
movingAvg myAvgs[4] = {6, 6, 6, 6};

// could also code:
// movingAvg myAvgs[] = {6, 6, 6, 6};
// in which case the array length will be equal to the number of initializers
// given, 4 again in this case.

void setup()
{
    Serial.begin(115200);
    for (uint8_t i=0; i<sizeof(myAvgs)/sizeof(myAvgs[0]); i++)
        myAvgs[i].begin();
}

void loop()
{
    for (uint8_t i=0; i<sizeof(myAvgs)/sizeof(myAvgs[0]); i++)
    {
        int r = random(100);
        int a = myAvgs[i].reading(r);
        Serial << "myAvgs[" << i << "] r=" << r << " avg=" << a << endl;
    }
    Serial << endl;
    delay(2000);
}
```
I'm leaning towards just closing the PR.

**Pull request closed without merging**
